exports.secretOfKey = "RSTRSsecretkey";

exports.USER_ROLES = {
  ADMIN: 0,
  PASSENGER: 1,
  CHECKER: 2,
};

exports.APPLICATION_STATUSES = {
  APPLICATION_PENDING: 0,
  PAYMENT_PENDING: 1,
  PAYMENT_APPROVAL_PENDING: 2,
  APPLICATION_REJECTED: 3,
  ACTIVE: 4,
  PAYMENT_REJECTED: 5,
};
